### ISSUE TITLE
請教如何針對高解析度照片上色?

### ISSUE THREAD

**Issue by ghost** [MenghanXia/DisentangledColorization#3]
你好
我嘗試在disco平台上，將一張1920 x 1080 大小的黑白照片上色，卻一直無法成功
是不是該平台目前最高只能設定在512 x 512?

另外如果想在本地上訓練+上色，是否有規定照片大小?
電腦規格為win10 i9-12900K RTX3080
謝謝

**Comment by MenghanXia** [comment]
首先，我们在Github和HuggingFace上提供的模型都是支持测试任意分辨率图像的，因为内置代码会将输入图像转成256x256或512x512之后运行上色算法，最后输出时会转回原始输入分辨率。所以，对于你遇到的问题，可能是由于HuggingFace平台的计算限制。建议你把1920x1080的图像缩小一些试试，比如960x540。
此外，如果在本地重新训练模型，建议使用256x256的图像大小并适当调整batch size，否则GPU内存可能会不足。

**Comment by ghost** [comment]
回報一下本地端測試
執行sh ./scripts/inferece.sh時候，可以成功上色，但輸出size為256
(這邊只採用你預設的data做測試)
因此我在inferece.sh裡面，加了--no_resize，重新執行一次
結果GPU內存不夠，想請問還要改哪邊的參數才能順利執行不縮小輸出格式?
謝謝

**Comment by MenghanXia** [comment]
在我们Github上的代码中，--no_resize意味着上色模型直接在原始输入分辨率上做inference，这时如果分辨率过大则会出现GPU内存不够的问题。建议适当缩小输入图像的分辨率再测试，比如在单机8G GPU的情况下，能直接在400x600上运行上色推理。

**Comment by ghost** [comment]
了解，但我目前的需求是，不更動現有的圖像尺寸，單純上色。
那看起來現階段只剩deoldify符合需求。謝謝你
